# A Docker image to be used to build your app
image: node:lts

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

stages:
  - test
  - pages

test:
  stage: test
  script:
    - export PATH=$PATH:./node_modules/.bin
    - npm ci
    - eleventy --input=src --output=public
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH

pages:
  stage: pages
  script:
    - export PATH=$PATH:./node_modules/.bin
    - npm ci
    - eleventy --input=src --output=public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
