name: chris-blog
env_file:
  - .env
services:
  node:
    type: node
    via: apache
# proxy:
#   node:
#     - chris-blog.lndo.site:8080
config:
  node: 16
  build:
    - npm install
  globals: []
tooling:
  eleventy:
    service: node
    cmd: eleventy
  node:
    service: node
    cmd: node
  npm:
    service: node
    cmd: npm
