name: chris-blog
env_file:
  - .env
services:
  node:
    type: node
    scanner: false
proxy:
  node:
    - chris-blog.lndo.site:80
config:
  node: 16
  build:
    - npm install
  command:
    - "npm run dev:*"
tooling:
  eleventy:
    service: node
    cmd: eleventy
  tailwind:
    service: node
    cmd: tailwindcss -i ./src/styles/main.css -o ./public/style.css
  node:
    service: node
    cmd: node
  npm:
    service: node
    cmd: npm
